### ISSUE TITLE
Error: StringIndexOutOfBoundsException at YarnChild.main

### ISSUE THREAD

**Issue by alv1234** [StefanPapp/bigdata_buch#1]
Beim Ausführen des Befehls in Listing 3.34 führt er den Job zwar aus, bricht ihn aber mit Status "failed".
Launched map tasks: 4
Failed map tasks: 4

Im Log bekomme ich diese Fehlermeldung:

Error: java.lang.StringIndexOutOfBoundsException: begin 10, end 13, length 0 at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3107) at java.base/java.lang.String.substring(String.java:1873) at de.jofre.grades.GradesMapper.map(GradesMapper.java:15) at de.jofre.grades.GradesMapper.map(GradesMapper.java:9) at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145) at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:763) at org.apache.hadoop.mapred.MapTask.run(MapTask.java:339) at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:162) at java.base/java.security.AccessController.doPrivileged(Native Method) at java.base/javax.security.auth.Subject.doAs(Subject.java:423) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491) at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:157)

Irgendeine Idee, wie ich das Debuggen kann?

**Comment by alv1234** [comment]
Ich konnte es lösen, ein Hinweis war die Klasse de.jofre.grades.GradesMapper.map. Hier vergas ich die if-Clause zum Überprüfen ob überhaupt ein String vorhanden ist. Beim Copy & Paste vom pdf ist wohl Code verloren gegangen. Jetzt funktionert es!
